# Site settings
title: Where on Earth is Piers ...Now?
email: piers@ompka.net
description: > # this means to ignore newlines until "baseurl:"
  Where on earth is Piers, My projects, and bits &apos;n bobs
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://piersharding.com" # the base hostname & protocol for your site
twitter_username: Piers
github_username:  piersharding
googleplus_username:  PiersHarding

# Build settings
markdown: kramdown
